accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('user_profile/<str:username>/', views.user_profile, name='user_profile'),
    path('edit_profile/<str:username>/', views.edit_profile, name='edit_profile'),
]

gameize/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('games.urls', namespace='games')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('', views.game_list, name='game_list'),
    path('create_game/', views.create_game, name='create_game'),
    path('game_detail/<int:pk>/', views.game_detail, name='game_detail'),
    path('update_game/<int:pk>/', views.update_game, name='update_game'),
    path('delete_game/<int:pk>/', views.delete_game, name='delete_game'),
    path('update_item/', views.updateItem, name='update_item'),
    path('cart/', views.cart, name='cart'),
    path('ckeckout/', views.checkout, name='checkout'),
    path('process_order/', views.process_order, name='process_order'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    avatar = models.ImageField(null=True, blank=True, default='default_pic.png')
    website = models.URLField(max_length=200, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control'})

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar', 'bio', 'website')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['bio'].widget.attrs.update({'class': 'form-control', 'cols': '50', 'rows': '2'})
        self.fields['website'].widget.attrs.update({'class': 'form-control'})

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login,logout,authenticate
from .forms import UserCreateForm, ProfileForm
from .decorators import unauthenticated_user, user_permission
from .models import Profile
from django.contrib.auth.models import User

# Create your views here.
@unauthenticated_user
def signup(request):
    form = UserCreateForm()

    if request.method == 'POST':
        form = UserCreateForm(request.POST)

        if form.is_valid():
            user = form.save()
            profile = Profile.objects.create(user=user)
            return redirect('accounts:login')

    return render(request, 'accounts/signup.html', {'form': form})

@unauthenticated_user
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('games:game_list')
        else:
            messages.info(request, 'Username or password is incorrect')

    return render(request, 'accounts/login.html', {})

@login_required
def logout_user(request):
    logout(request)
    return redirect('games:game_list')

def user_profile(request, username):
    user = User.objects.get(username__iexact=username)
    return render(request, 'accounts/user_profile.html', {'target_user': user})

@user_permission
@login_required
def edit_profile(request, username):
    user = User.objects.get(username__iexact=username)
    form = ProfileForm(instance=user.profile)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=user.profile)

        if form.is_valid():
            form.save()
            return redirect('accounts:user_profile', username=username)

    return render(request, 'accounts/edit_profile.html', {'form': form})

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% block content %}

<div class="form-container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h3>{{user.username}}</h3>
        <div>
            <img class="profile-pic mb-3" src="{{user.profile.avatar.url}}">
        </div>
        <div class="form-group">
            {{form.avatar.label}}
            {{form.avatar}}
        </div>
        <div class="form-group">
            {{form.bio.label}}
            {{form.bio}}
        </div>
        <div class="form-group">
            {{form.website.label}}
            {{form.website}}
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>


{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

<div class="form-container">
    <h1>Log In</h1>
    <form method="POST" autocomplete="off">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">Username</label>
            <input class="form-control" type="text" name="username">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input class="form-control" type="password" name="password">
        </div>
        <button type="submit" class="btn btn-primary">Log In</button>
    </form>
    <p class="mt-2">You don't have an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
</div>


{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}

<div class="form-container">
    <h1>Sign Up</h1>
    <form method="POST" class='mt-3'>
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group field-group">
                {{form.username.label}}
                {{form.username}}
            </div>
            <div class="form-group ml-4 field-group">
                {{form.email.label}}
                {{form.email}}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group field-group">
                {{form.password1.label}}
                {{form.password1}}
            </div>
            <div class="form-group ml-4 field-group">
                {{form.password2.label}}
                {{form.password2}}
            </div>
        </div>
        <button type="submit" class="btn btn-primary mt-2">Sign up</button>
    </form>
    <p class="mt-2">Already have an account? <a href="{% url 'accounts:login' %}">Log In</a></p>
</div>

{% endblock %}

accounts/templates/accounts/user_profile.html
{% extends 'base.html' %}
{% block content %}

<div class="profile-container">
    <div class='profile-header'>
        <img class="profile-pic" src="{{target_user.profile.avatar.url}}">
        <div class="user-info">
            <h3>{{target_user.username}}</h3>
            <p>{{target_user.profile.bio}}</p>
            <p>Website: {{target_user.profile.website}}</p>
            {% if target_user == user %}
                <a class="btn btn-secondary" href="{% url 'accounts:edit_profile' username=user.username %}">Edit profile</a>
                <a class="btn btn-secondary" href="{% url 'accounts:logout' %}">Log Out</a>
            {% endif %}
        </div>
    </div>

    <div class="game-list-container mt-4">
        {% for game in target_user.games.all %}
            <div class="card game-container">
                <a href="{% url 'games:game_detail' pk=game.pk %}"><img class="card-img-top" src="{{game.cover_image.url}}" alt="Game cover"></a>
                <div class="card-body">
                    <h5 class="card-title">{{game.title}}</h5>
                    <p class="card-text">{{game.short_description}}</p>
                    <p class="text-light">{{game.developer}}</p>
                    {% if target_user == user %}
                        <div class="d-flex">
                            <a class="btn btn-success" href="{% url 'games:update_game' pk=game.pk %}">Update</a>
                            <a class="btn btn-danger ml-2" href="{% url 'games:delete_game' pk=game.pk %}">Delete</a>
                        </div>
                    {% else %}
                        <button class="btn btn-success cart-btn" data-game="{{game.id}}" data-action="add">Add to Cart</button>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}