accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('user_profile/<str:username>/', views.user_profile, name='user_profile'),
    path('edit_profile/<str:username>/', views.edit_profile, name='edit_profile'),
]

gameize/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('games.urls', namespace='games')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('', views.game_list, name='game_list'),
    path('create_game/', views.create_game, name='create_game'),
    path('game_detail/<int:pk>/', views.game_detail, name='game_detail'),
    path('update_game/<int:pk>/', views.update_game, name='update_game'),
    path('delete_game/<int:pk>/', views.delete_game, name='delete_game'),
    path('update_item/', views.updateItem, name='update_item'),
    path('cart/', views.cart, name='cart'),
    path('ckeckout/', views.checkout, name='checkout'),
    path('process_order/', views.process_order, name='process_order'),
]

games/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.
class Game(models.Model):
    STATUS = [
        ('Released', 'Released'),
        ('In Development', 'In Development'),
        ('Early Access', 'Early Access')
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='games')
    title = models.CharField(max_length=150, unique=True)
    short_description = models.TextField(blank=True, null=True)
    description = RichTextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    cover_image = models.ImageField(blank=True, null=True)
    price = models.DecimalField(decimal_places=2, max_digits=5)
    release_status = models.CharField(choices=STATUS, max_length=200)
    developer = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.title

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='orders', blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=True)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)

class OrderItem(models.Model):
    game = models.ForeignKey(Game, on_delete=models.SET_NULL, related_name='order_items', blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def get_total(self):
        return self.game.price * self.quantity

games/forms.py
from django import forms
from .models import Game

class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ('title', 'short_description', 'description', 'cover_image', 'price', 'release_status', 'developer')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control'})
        self.fields['developer'].widget.attrs.update({'class': 'form-control'})
        self.fields['short_description'].widget.attrs.update({'class': 'form-control', 'cols': '50', 'rows': '2'})
        self.fields['price'].widget.attrs.update({'class': 'form-control'})
        self.fields['release_status'].widget.attrs.update({'class': 'form-control'})

games/views.py
from django.shortcuts import render, redirect
from .forms import GameForm
from .models import Game, Order, OrderItem
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import json
import datetime
from accounts.decorators import action_permission


# Create your views here.
def game_list(request):
    games = Game.objects.all().order_by('-created_at')
    item_count = 0

    if request.user.is_authenticated:
        order, created = Order.objects.get_or_create(user=request.user, complete=False)
        items = order.orderitem_set.all()

        for item in items:
            item_count += item.quantity

    return render(request, 'games/game_list.html', {'games': games, 'item_count': item_count})

@login_required
def create_game(request):
    form = GameForm()

    if request.method == 'POST':
        form = GameForm(request.POST, request.FILES)

        if form.is_valid():
            game = form.save(commit=False)
            game.user = request.user
            game.save()
            return redirect('games:game_list')

    return render(request, 'games/create_game.html', {'form': form})

def game_detail(request, pk):
    game = Game.objects.get(id=pk)
    return render(request, 'games/game_detail.html', {'game': game})

@login_required
@action_permission
def update_game(request, pk):
    game = Game.objects.get(id=pk)
    form = GameForm(instance=game)

    if request.method == 'POST':
        form = GameForm(request.POST, request.FILES, instance=game)

        if form.is_valid():
            form.save()
            return redirect('accounts:user_profile', username=request.user.username)

    return render(request, 'games/create_game.html', {'form': form})

@login_required
@action_permission
def delete_game(request, pk):
    game = Game.objects.get(id=pk)

    if request.method == 'POST':
        game.delete()
        return redirect('accounts:user_profile', username=request.user.username)

    return render(request, 'games/delete_game.html', {'game': game})

@login_required
def updateItem(request):
    data = json.loads(request.body)
    gameId = data['gameId']
    action = data['action']

    game = Game.objects.get(id=gameId)
    order, created = Order.objects.get_or_create(user=request.user, complete=False)
    orderItem, created = OrderItem.objects.get_or_create(order=order, game=game)
    items = order.orderitem_set.all()

    if action == 'add':
        orderItem.quantity += 1
    elif action == 'remove':
        orderItem.quantity -= 1
    
    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    item_count = 0
    for item in items:
        item_count += item.quantity

    game_data = {'item_count': item_count}

    return JsonResponse(game_data, safe=False)

@login_required
def cart(request):
    order, created = Order.objects.get_or_create(user=request.user, complete=False)
    items = order.orderitem_set.all()

    total = 0
    item_count = 0
    for item in items:
        total += (item.game.price) * item.quantity
        item_count += item.quantity

    return render(request, 'games/cart.html', {'items': items, 'total': total, 'item_count': item_count})

@login_required
def checkout(request):
    order, created = Order.objects.get_or_create(user=request.user, complete=False)
    items = order.orderitem_set.all()

    total = 0
    item_count = 0
    for item in items:
        total += (item.game.price) * item.quantity
        item_count += item.quantity

    return render(request, 'games/checkout.html', {'items': items, 'total': total, 'item_count': item_count})

@login_required
def process_order(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    order, created = Order.objects.get_or_create(user=request.user, complete=False)
    total = float(data['total'])
    order.transaction_id = transaction_id

    items = order.orderitem_set.all()
    check_total = 0
    for item in items:
        check_total += float(item.game.price) * float(item.quantity)

    if total == float(check_total):
        order.complete = True
    order.save()

    return JsonResponse('Payment complete', safe=False)

games/templates/games/cart.html
{% extends 'base.html' %}
{% block content %}

<div class="cart-container">
    <div class="cart-items">
        <h3>Items</h3>
        {% for item in items %}
        <div class="cart-game-container mt-4 ml-auto mr-auto">
            <img class="cart-img" src="{{item.game.cover_image.url}}">
            <div class="cart-game-info">
                <h4>{{item.game.title}}</h4>
                <p>${{item.game.price}}</p>
                <div class="quantity mb-4">
                    <button class="btn btn-primary btn-sm mr-1 cart-btn quantity-btn-remove" data-game="{{item.game.id}}" data-action="remove">-</button>
                    <span class="quantity-text" data-quantity="{{item.quantity}}">{{item.quantity}}</span>
                    <button class="btn btn-primary btn-sm ml-1 cart-btn quantity-btn-add" data-game="{{item.game.id}}" data-action="add">+</button>
                </div>
                <h5>Total</h5>
                <p>${{item.get_total}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="cart-info">
        <h3>Order</h3>
        <p class="cart-item-count">Items: {{item_count}}</p>
        <p class="global-total">Total: ${{total}}</p>
        <a href="{% url 'games:checkout' %}" class="btn btn-success">Checkout</a>
        <a href="{% url 'games:game_list' %}" class="btn btn-primary mt-2">Continue Shopping</a>
    </div>
</div>

{% endblock %}

games/templates/games/checkout.html
{% extends 'base.html' %}
{% block content %}

<div class="cart-container">
    <div class="cart-items">
        <h3>Order Summary</h3>
        {% for item in items %}
        <div class="cart-game-container mt-4 ml-auto mr-auto">
            <img class="cart-img" src="{{item.game.cover_image.url}}">
            <div class="cart-game-info">
                <h4>{{item.game.title}}</h4>
                <p>${{item.game.price}}</p>
                <h5>Total</h5>
                <p>${{item.get_total}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="cart-info">
        <h3>Payment</h3>
        <p>Items: {{item_count}}</p>
        <p>Total: ${{total}}</p>
        <a href="{% url 'games:cart' %}" class="btn btn-primary mt-2 mb-2">Return to Cart</a>
        <div id="paypal-button-container"></div>
        <!-- <a href="#" class="btn btn-success mt-2 payment-btn">Make Payment</a> -->
    </div>
</div>
<script src="https://www.paypal.com/sdk/js?client-id=AVEp4R8GnkuIKeB1cjoLLRxVAj83oxKJxZwuu67e1arQf9pIZbxFmjdghNWW403Fnsdwgx5HkqEMdgT5&currency=USD"></script>

<script>
    const total = '{{total}}'
    // Render the PayPal button into #paypal-button-container
    paypal.Buttons({

        // Set up the transaction
        createOrder: function(data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: parseFloat(total).toFixed(2)
                    }
                }]
            });
        },

        // Finalize the transaction
        onApprove: function(data, actions) {
            return actions.order.capture().then(function(details) {
                // Show a success message to the buyer
                submitPaymentData();
            });
        }


    }).render('#paypal-button-container');
</script>

<script type="text/javascript">
    const paymentBtn = document.querySelector('.payment-btn');

    // paymentBtn.addEventListener('click', function(e) {
    //     submitPaymentData();
    // }) 

    function submitPaymentData() {
        console.log('Payment clicked');

        const url = '/process_order/'
        fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken,
            },
            body: JSON.stringify({'total': total})
        })
        .then(response => {
            return response.json()
        })
        .then(data => {
            console.log('Success:', data);
            alert('Transaction completed');
            window.location.href = "{% url 'games:game_list' %}";
        })
    }
</script>

{% endblock %}

games/templates/games/create_game.html
{% extends 'base.html' %}
{% block content %}

<div class="form-container game-form-container">
    <h1>Upload Game</h1>
    <form method='POST' class="mt-3" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        <div class="game-form-group">
            {{form.title.label}}
            {{form.title}}
        </div>
        <div class="game-form-group">
            {{form.developer.label}}
            {{form.developer}}
        </div>
        <div class="game-form-group">
            {{form.short_description.label}}
            <p class="text-secondary">This will be shown when linking your project.</p>
            {{form.short_description}}
        </div>
        <div class="game-form-group">
            {{form.description.label}}
            <p class="text-secondary">This is the main content of your game.</p>
            {{form.description}}
        </div>
        <div class="game-form-group">
            {{form.cover_image.label}}
            {{form.cover_image}}
        </div>
        <div class="form-row">
            <div class="game-form-group field-group">
                {{form.price.label}}
                {{form.price}}
            </div>
            <div class="game-form-group field-group ml-4">
                {{form.release_status.label}}
                {{form.release_status}}
            </div>
        </div>
        <button type='submit' class="btn btn-primary">Submit</button>
    </form>
</div>

{% endblock %}

games/templates/games/delete_game.html
{% extends 'base.html' %}
{% block content %}

<div class="form-container">
    <h5 class="card-title">Delete Game?</h5>
    <p class="card-text">Deleting a game will permanently delete it from the database.</p>
    <form method="POST" action="{% url 'games:delete_game' pk=game.pk %}">
        {% csrf_token %}
        <a class="btn btn-secondary" href="{% url 'accounts:user_profile' username=user.username %}">Keep Game</a>
        <button type="submit" class="btn btn-danger">Delete Game</button>
    </form>
</div>

{% endblock %}

games/templates/games/game_detail.html
{% extends 'base.html' %}
{% block content %}

<div class='game-block'>
    <div class="game-img-container">
        <img class="game-img" src="{{ game.cover_image.url }}">
    </div>
    <div class="game-body d-flex">
        <div class="game-desc">
            {{game.description|safe}}
        </div>
        <div class="game-data">
            <div class="sell-game mb-3">
                <h3>Purchase</h3>
                <div class="d-flex">
                    {% if user == game.user %}
                        <div class="d-flex">
                            <a class="btn btn-success" href="{% url 'games:update_game' pk=game.pk %}">Update</a>
                            <a class="btn btn-danger ml-2" href="{% url 'games:delete_game' pk=game.pk %}">Delete</a>
                        </div>
                    {% else %}
                        <button class="btn btn-success cart-btn" data-game="{{game.id}}" data-action="add">Add to Cart</button>
                    {% endif %}
                    <span class="ml-2 mt-1">${{game.price}}</span>
                </div>
            </div>
            <p>Developer: {{game.developer}}</p>
            <p>State: {{game.release_status}}</p>
            <p>Published by: <a class="link" href="{% url 'accounts:user_profile' username=game.user.username %}">{{game.user}}</a></p>
        </div>
    </div>
</div>

{% endblock %}

games/templates/games/game_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container mt-4">
    <h1>Top Games</h1>
    <div class="game-list-container mt-4">
        {% for game in games %}
            <div class="card game-container">
                <a href="{% url 'games:game_detail' pk=game.pk %}"><img class="card-img-top" src="{{game.cover_image.url}}" alt="Game cover"></a>
                <div class="card-body">
                    <h5 class="card-title">{{game.title}}</h5>
                    <p class="card-text">{{game.short_description}}</p>
                    <p class="text-light">{{game.developer}}</p>
                    {% if user == game.user %}
                        <div class="d-flex">
                            <a class="btn btn-success" href="{% url 'games:update_game' pk=game.pk %}">Update</a>
                            <a class="btn btn-danger ml-2" href="{% url 'games:delete_game' pk=game.pk %}">Delete</a>
                        </div>
                    {% else %}
                        <button class="btn btn-success cart-btn" data-game="{{game.id}}" data-action="add">Add to Cart</button>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}