accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('user_profile/<str:username>/', views.user_profile, name='user_profile'),
    path('edit_profile/<str:username>/', views.edit_profile, name='edit_profile'),
]

gameize/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('games.urls', namespace='games')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

games/urls.py
from django.urls import path
from . import views

app_name = 'games'

urlpatterns = [
    path('', views.game_list, name='game_list'),
    path('create_game/', views.create_game, name='create_game'),
    path('game_detail/<int:pk>/', views.game_detail, name='game_detail'),
    path('update_game/<int:pk>/', views.update_game, name='update_game'),
    path('delete_game/<int:pk>/', views.delete_game, name='delete_game'),
    path('update_item/', views.updateItem, name='update_item'),
    path('cart/', views.cart, name='cart'),
    path('ckeckout/', views.checkout, name='checkout'),
    path('process_order/', views.process_order, name='process_order'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="https://kit.fontawesome.com/1b2de11c6b.js" crossorigin="anonymous"></script>
    <script type="text/javascript">
        const user = '{{request.user}}';

        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getToken('csrftoken');
    </script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark main-nav">
        <a class="navbar-brand" href="{% url 'games:game_list' %}">Gameize</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto w-100 justify-content-end">
            {% if user.is_authenticated %}
                <li class="nav-item mr-auto">
                    <a class="nav-link" href="{% url 'games:create_game' %}">Upload Game</a>
                </li>
                <li class="nav-item">
                    <div class="profile-pic-container d-flex">
                        <a href="{% url 'accounts:user_profile' username=user.username %}"><img class="small-profile-pic" src="{{user.profile.avatar.url}}"></a>
                        <a href="{% url 'accounts:user_profile' username=user.username %}" class="nav-link">{{user.username}}</a>
                    </div>
                </li>
                <li class="nav-item">
                    <div class="position-relative">
                        <a class="nav-link" href="{% url 'games:cart' %}"><i class="fas fa-shopping-cart"></i></a>
                        <span class="position-absolute cart-circle">{% current_order_items request %}</span>
                    </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-primary" href="{% url 'accounts:signup' %}">Sign Up</a>
                </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    {% block content %}

    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'js/cart.js' %}" type="text/javascript"></script>
</body>
</html>